# Generated by Django 5.1.5 on 2025-02-02 06:36

import django.utils.timezone
import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0005_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category_objects',
            field=models.ManyToManyField(to='instructor.category'),
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
